blank_issues_enabled: true

contact_links:
  - name: Godot issues
    url: https://github.com/godotengine/godot/issues
    about: Please report issues that also happen without gd-clouds on the Godot repository, not here.

  - name: Godot community channels
    url: https://godotengine.org/community
    about: Please ask for general help with Godot on one of the community channels, not here.
